
spring:
  application:
    name: camel-pipeline

camel:
  main:
    name: camel-pipeline
  springboot:
    main-run-controller: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,camelroutes

app:
  source:
    # Puedes sobreescribir via env: APP_SOURCE_URL
    url: http://localhost:8082/api/usuarios/123
  target:
    # Puedes sobreescribir via env: APP_TARGET_URL
    url: http://localhost:8083/api/destino
  poll:
    # Puedes sobreescribir via env: APP_POLL_PERIOD
    period: 10000
